// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBT3g49nJZFqn6rzZgQWbcDPINbxslftTM',
    appId: '1:387237623265:web:caa39286587da73efdcea0',
    messagingSenderId: '387237623265',
    projectId: 'doctor-hunt-13c53',
    authDomain: 'doctor-hunt-13c53.firebaseapp.com',
    storageBucket: 'doctor-hunt-13c53.firebasestorage.app',
    measurementId: 'G-K9PWF4D3ZJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAM3JCTfwVUM6hEbCgmXUv_15Ww4UFxkbg',
    appId: '1:387237623265:android:354c11b86dc4c1f1fdcea0',
    messagingSenderId: '387237623265',
    projectId: 'doctor-hunt-13c53',
    storageBucket: 'doctor-hunt-13c53.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC75W60VOx-jj1hEZTYXFz1TyEX3E9lwLY',
    appId: '1:387237623265:ios:45a320cb107199dcfdcea0',
    messagingSenderId: '387237623265',
    projectId: 'doctor-hunt-13c53',
    storageBucket: 'doctor-hunt-13c53.firebasestorage.app',
    iosBundleId: 'com.example.doctorApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC75W60VOx-jj1hEZTYXFz1TyEX3E9lwLY',
    appId: '1:387237623265:ios:45a320cb107199dcfdcea0',
    messagingSenderId: '387237623265',
    projectId: 'doctor-hunt-13c53',
    storageBucket: 'doctor-hunt-13c53.firebasestorage.app',
    iosBundleId: 'com.example.doctorApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBT3g49nJZFqn6rzZgQWbcDPINbxslftTM',
    appId: '1:387237623265:web:79216730c99331c1fdcea0',
    messagingSenderId: '387237623265',
    projectId: 'doctor-hunt-13c53',
    authDomain: 'doctor-hunt-13c53.firebaseapp.com',
    storageBucket: 'doctor-hunt-13c53.firebasestorage.app',
    measurementId: 'G-BP2DTT8M3L',
  );
}
